#!/usr/bin/env bash
# owner: pipeline-contracts-template
# generate-coverage.sh — Walk the filesystem and regenerate
# docs/contracts/_coverage.md as a deterministic table mapping every
# governance script/hook to its covering contract.
#
# Sources scanned (recursive):
#   scripts/**/*.sh                    (excluding any _* component in path)
#   .claude/hooks/**/*.sh
# Contracts read:
#   docs/contracts/*.contract.md       (full WS3a shape, owns: frontmatter)
#   docs/contracts/*.cli-contract.md   (lighter WS5 shape, script: frontmatter)
#
# Idempotent by construction: LC_ALL=C sort, no timestamps, stable formatting.
# Per WS5 design §D6. Portable: no GNU-specific find flags.
# Compatible with bash 3.2 (macOS default) — no declare -A.

set -uo pipefail
ROOT="$(pwd)"
OUT="$ROOT/docs/contracts/_coverage.md"
mkdir -p "$(dirname "$OUT")"

# Helper: list source files under a root, relative to it, excluding any _* component
list_sources() {
  local base="$1"
  [ -d "$base" ] || return 0
  ( cd "$base" && find . -type f -name '*.sh' -print 2>/dev/null ) \
    | sed 's|^\./||' \
    | grep -v -E '(^|/)_' \
    | LC_ALL=C sort
}

scripts=$(list_sources "$ROOT/scripts")
hooks=$(list_sources "$ROOT/.claude/hooks")

# Delegate all contract parsing and table-row generation to Python.
# Python reads contracts, checks for duplicate ownership, then for each
# script/hook path emits a pipe-delimited row: "rel|contract|shape"
# or "rel|MISSING|—" if uncovered.
# Exits non-zero on duplicate-ownership.
table_rows=$(python3 - "$ROOT" "$scripts" "$hooks" <<'PYEOF'
import sys, os, yaml, glob, re

root    = sys.argv[1]
scripts = [s for s in sys.argv[2].split("\n") if s]
hooks   = [h for h in sys.argv[3].split("\n") if h]

contracts_dir = os.path.join(root, "docs", "contracts")
coverage = {}   # path -> (contract_rel, shape)
errors   = []

if os.path.isdir(contracts_dir):
    for path in sorted(glob.glob(os.path.join(contracts_dir, "*.md"))):
        if not (path.endswith(".contract.md") or path.endswith(".cli-contract.md")):
            continue
        rel = os.path.relpath(path, root)
        try:
            with open(path) as f:
                text = f.read()
        except OSError:
            continue
        parts = re.split(r'^---\s*$', text, maxsplit=2, flags=re.MULTILINE)
        if len(parts) < 3:
            continue  # malformed frontmatter — validator handles; skip for coverage
        try:
            fm = yaml.safe_load(parts[1]) or {}
        except yaml.YAMLError:
            continue
        if not isinstance(fm, dict):
            continue
        shape = "cli" if path.endswith(".cli-contract.md") else "full"
        covered = []
        if shape == "cli" and "script" in fm and fm["script"]:
            covered.append(str(fm["script"]))
        elif shape == "full" and "owns" in fm and isinstance(fm["owns"], list):
            covered.extend(str(o) for o in fm["owns"] if o)
        for c in covered:
            if c in coverage:
                errors.append(
                    f"duplicate ownership: '{c}' claimed by both {coverage[c][0]} and {rel}"
                )
            coverage[c] = (rel, shape)

if errors:
    for e in errors:
        print(f"DUPLICATE-OWNERSHIP: {e}", file=sys.stderr)
    sys.exit(1)

def row(rel):
    if rel in coverage:
        contract, shape = coverage[rel]
    else:
        contract, shape = "MISSING", "—"
    print(f"{rel}|{contract}|{shape}")

for s in scripts:
    row(f"scripts/{s}")
for h in hooks:
    row(f".claude/hooks/{h}")
PYEOF
)
py_rc=$?
[ $py_rc -eq 0 ] || { echo "generate-coverage: contract parsing failed" >&2; exit $py_rc; }

# Emit the manifest
{
  echo "# Governance-script contract coverage"
  echo ""
  echo "<!-- AUTO — regenerated by scripts/generate-coverage.sh from filesystem scan. -->"
  echo "<!-- Sources: scripts/**/*.sh (excluding _* components), .claude/hooks/**/*.sh, docs/contracts/*.contract.md, docs/contracts/*.cli-contract.md -->"
  echo ""
  echo "| Script / Hook | Contract | Shape |"
  echo "|---|---|---|"
  while IFS='|' read -r rel contract shape; do
    [ -z "$rel" ] && continue
    echo "| $rel | $contract | $shape |"
  done <<<"$table_rows"
} > "$OUT"

exit 0
